apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::658018844294:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-W7UZLTBQ3O50
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::658018844294:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-26T14:05:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1657"
  uid: 348f5834-3111-464a-9cf8-0af11f33071c
